version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qrixie_web
    ports:
      - '3010:3000'
    labels:
      - traefik.http.routers.qrixie.rule=Host(`qrixie.com`)
      - traefik.http.routers.qrixie.tls=true
      - traefik.http.routers.qrixie.tls.certresolver=le
      - traefik.http.services.qrixie.loadbalancer.server.port=3010
      - traefik.docker.network=web

networks:
  default:
    external:
      name: web
